<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/PdfTemplates
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-pdf-invoice-pro
 */
?>
<?php $fonts = $block->getFonts();?>
<?php if (!empty($fonts)) : ?>

<p id="mteditor_fonts" style="display: none">
    <?php foreach ($fonts as $font) : ?>
    @font-face {
        font-family: '<?php echo $font['code'];?>';
        src: url('<?php echo $font['url'];?>') format('TrueType');
        font-weight: normal;
    }
    <?php endforeach; ?>
</p>
<?php endif; ?>