<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/PdfTemplates
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-pdf-invoice-pro
 */
?>
<?php $errors = $block->getErrorMessages();?>
<?php if (!empty($errors)) : ?>
    <div class="mteditor-error-msg">
        <?php foreach ($errors as $error) : ?>
            <div class="alert alert-danger"><?php echo $error->getText() ?></div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>