<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/PdfTemplates
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-pdf-invoice-pro
 */
?>
<div id="" class="element_qrcode layer-qrcode" data-resizable="true" data-resizable-handle="keep-ratio" data-lock="false" style="width: 80px; height: 80px">
    <img src="<?php echo $block->getViewFileUrl('Magetrend_PdfTemplates::images/mteditor/qrcode.png')?>" width="100%" height="100%" />
</div>