<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/PdfTemplates
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-pdf-invoice-pro
 */
?>
<?php
$totalConfig = $block->getTotalConfig();
?>
<div id="" data-resizable="true" data-resizable-handle="table" class="pdf-element element_total"style="height: auto !important;">
    <table cellpadding="0" cellspacing="0" width="100%" height="100%" class="pdf-table" style="border-width: 0; border-style: solid">
        <?php if (!empty($totalConfig)) : ?>
            <?php foreach ($totalConfig as $key => $total) : ?>
            <tr class="pdf-table-item row-<?php echo $total['source_field']; ?> <?php if (strpos($total['source_field'], 'grand_total') === false): ?> pdf-table-item-total <?php else: ?> pdf-table-item-grand-total <?php endif; ?>">
                <td class="pdf-table-label translate_<?php echo $total['source_field']; ?>"><?php echo $total['title']; ?></td>
                <td class="pdf-table-value"><?php echo $total['dummy_value']; ?></td>
            </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
</div>
