<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/PdfTemplates
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-pdf-invoice-pro
 */

$columnConfig = $block->getColumnConfig();

?>
<div data-resizable="true" data-resizable-handle="table" class="pdf-element element_track" id="" style="height: auto !important;">
    <table cellpadding="0" cellspacing="0" width="100%" height="100%" class="pdf-table element-track-table" style="height: 120px; border-width: 0; border-style: solid">
        <tr class="pdf-table-track-header">
            <?php foreach ($columnConfig as $key => $column) : ?>
            <th class="pdf-translate-<?php echo $key; ?> column-<?php echo $key; ?>"><?php echo $column['label'] ?></th>
            <?php endforeach; ?>
        </tr>
        <tr class="pdf-table-track line-1">
            <?php foreach ($columnConfig as $key => $column) : ?>
            <td><?php echo $column['default']['item_1']; ?></td>
            <?php endforeach; ?>
        </tr>

        <tr class="pdf-table-track line-2">
            <?php foreach ($columnConfig as $key => $column) : ?>
                <td><?php echo $column['default']['item_2']; ?></td>
            <?php endforeach; ?>
        </tr>
    </table>
</div>
